#!/bin/bash

fieldsum=$1
num_entries=$2

average=$(expr $fieldsum / $num_entries)

echo "unrounded: $average"

if [[ $(expr $fieldsum % $num_entries) -ge $(expr $num_entries / 2 + $num_entries % 2) ]]; then
	((average++))
fi

echo $average
